# Generated by Django 5.2.4 on 2025-08-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('vehicle_Type', models.CharField()),
                ('year', models.IntegerField()),
                ('engine_capacity', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=10)),
                ('registration_city', models.CharField(max_length=20)),
                ('hybrid', models.CharField(max_length=5)),
                ('fuel_type', models.CharField(max_length=15)),
                ('distance_covered', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
